### ISSUE TITLE
Invitation to web standards meeting about a Screen Reader Automation API on 28th March 2022

### ISSUE THREAD

**Issue by zcorpan** [guidepup/guidepup#16]
Hi @cmorten, @rmhartog,

I came across `guidepup` on GitHub while looking for projects that automate screen readers. I’m part of a web standards [group called ARIA-AT](https://aria-at.w3.org/) that  is also looking into automating screen readers, for the purpose of conformance testing.

We're trying to standardize a new API to programmatically control screen readers that we hope will be implemented by vendors to unlock new functionality and to more reliably test the behavior of screen readers. 

We’d like to include the input of tooling authors like you. If you're interested in participating in this effort, you're very welcome to attend the next ARIA-AT Automation meeting on February 28 at 12pm PT / 3pm ET. See details here:

w3c/aria-at-automation#17

Thank you!

**Comment by zcorpan** [comment]
There has been a change of plans since we need some more time to prepare. The new tentative date is March 28. See https://github.com/w3c/aria-at/issues/622#issuecomment-1049760383

Apologies for the late change, and thanks for understanding.

**Comment by cmorten** [comment]
@zcorpan sounds awesome! Will try to attend 😄
