### ISSUE TITLE
Screen recording or NVDA virtual cursor on Windows GitHub Action runner?

### ISSUE THREAD

**Issue by ckundo** [guidepup/guidepup#57]
Hi @cmorten, curious if you've tried recording video of the screen to capture the NVDA cursor on WIndows. I've been able to do this with VoiceOver.js on macOS using the `screencapture` command, and I'm curious if there's something similar on Windows I can try. Closest I can see is Gamecenter (WIndows key + G). How would I pass these keystrokes using the `nvda` object, or otherwise? thx!

**Comment by cmorten** [comment]
Hey @ckundo  👋 

I looked at this a while back and IIRC there wasn't anything quite like `screencapture` for Windows which was quite frustrating! Win+Alt+G or Win+Alt+F are options, but have put together https://github.com/guidepup/guidepup/pull/58 where use `ffmpeg` instead which appears to be working well.

E.g. see attached video recorded on the GitHub Actions agent for NVDA + Chromium through Playwright.

https://github.com/guidepup/guidepup/assets/11313985/ffd03928-1bed-48bc-ac2a-090f351d872a

**Comment by cmorten** [comment]
See https://github.com/guidepup/guidepup/blob/0.19.0/examples/playwright-nvda/tests/chromium/chromium.spec.ts#L16 for example usage.

**Comment by ckundo** [comment]
@cmorten this is great, thank you! I'm going to try to stand this up in GitHub Actions.
