### ISSUE TITLE
Modifier is ignored in shortcuts using "+"

### ISSUE THREAD

**Issue by AnyMa** [guidepup/guidepup#64]
Sometimes, when executing the key combination "Shift+Tab" repeatedly in a loop, the modifier "Shift" is ignored and it just executes the "Tab".

**Comment by cmorten** [comment]
@AnyMa please could you confirm whether this is for NVDA or VoiceOver?

I've just pushed a change in 0.19.1 for `nvda.press(commandStr)` which fixes some issues with commands not being executed properly, would be good to know if this resolves your issue here with the Shift modifier!

**Comment by AnyMa** [comment]
Hi Craig! Thanks for your fast response and fix. I'll give it a try and let
you know!

**Comment by AnyMa** [comment]
oh BTW, the issue was for NVDA

**Comment by AnyMa** [comment]
Hi Craig! It's me again! well, very good news! both issues seem to be
fixed. thanks a lot for taking care and solving them so quickly! you rock!

[image: image.png]
