### ISSUE TITLE
Getting "const guidepup = new Guidepup(page);                    ^  TypeError: Guidepup is not a constructor" error message

### ISSUE THREAD

**Issue by GaneshSignet** [guidepup/guidepup#81]
# Issue

Setup:

- Node version: <replace_with_node_version (try `node --version`)>
- Guidepup version: <replace_with_guidepup_version>
- OS Platform: <replace_with_os_platform>
- OS Release: <replace_with_os_release_version>

## Details

> Please replace this quote block with the details of the feature / bug you wish to be addressed. If it is a bug please do your best to add steps to reproduce.

This is my code snippet

const { chromium } = require('playwright');
const {Guidepup} = require('@guidepup/playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  const guidepup = new Guidepup(page);

  // Serve the local HTML file
  const fileUrl = `file://${__dirname}/index.html`;
  await page.goto(fileUrl);

  // Run accessibility checks
  const accessibilityReport = await guidepup.checkAccessibility();
  console.log(JSON.stringify(accessibilityReport, null, 2));

  await browser.close();
})();

Package.json

{
  "name": "guide",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright": "^1.45.0"
  },
  "devDependencies": {
    "@guidepup/guidepup": "^0.22.3",
    "@guidepup/playwright": "^0.13.2",
    "@playwright/test": "^1.45.0"
  }
}

**Comment by cmorten** [comment]
Hi @GaneshSignet 👋 

I would recommend having a read of the docs, see https://www.guidepup.dev/docs/example

The code you have written is trying to use things that don’t exist, there is no `Guidepup` export nor `.checkAccessibility()` API in this project.

Your code example looks like might be a mix-up between this project and using Axe with Playwright, e.g. see https://playwright.dev/docs/accessibility-testing

I would recommend following the docs to understand how to use Guidepup, or can copy one of the examples from the repos, e.g. https://github.com/guidepup/guidepup-playwright/tree/main/examples
