### ISSUE TITLE
License conflict with FFmpeg

### ISSUE THREAD

**Issue by lucas-emery** [guidepup/guidepup#88]
## Details

> Hey, I stumbled upon your lib and I think it's great and want to use it for snapshot tests via your jest package. But there's a forced dependency on FFmpeg https://github.com/guidepup/guidepup/blob/f0f2e1005ae7e6945af4e0f0b5de241199ed977e/src/windows/record.ts#L6 that makes licensing weird and isn't really needed. 
Do you think you could maybe move the base guidepup API to a separate package so virtual-screen-reader doesn't bring over all these extra deps for windows and mac?

Thanks,
Lucas

**Comment by cmorten** [comment]
@lucas-emery I’ve done a bit of a refactor for various repos which hopefully resolves this.

If not shout and we can reopen

**Comment by lucas-emery** [comment]
Thank you very much for the quick delivery, I think I'll be able to test it tomorrow.

I'll let you know how it goes, thanks a lot for your work!
