### ISSUE TITLE
focus does not seem to transition to an iframe modal 

### ISSUE THREAD

**Issue by eevyatarr** [guidepup/guidepup#92]
# Issue

Setup:

- Node version: v16.15.0
- Guidepup version: 
@guidepup/guidepup@0.22.3
@guidepup/playwright@0.14.1
- OS Platform: macOS
- OS Release: sonoma 14.6.1

## Details
Hey
ive been trying to automate the 'book a demo' flow on our company website "evinced.com" and noticed that the voiceOver focus indicator does not transition to the modal that is opened upon clicking the "book a demo" button, at first I suspected an accessibility issue on our site (oh no! 🤯), but on manual testing with VoiceOver activated the focus moves just fine to the desired text box.

we now suspect that something with the communication with guidepup and/or playwright with the page does not manage the focus properly 

I've attached code that reproduces the issue both on our company site and also on a simpler custom-made page, both display the same issue:
on manual testing, the focus does move to the text box inside the iframe
but using the guidepup library the focus goes elsewhere

I hope that I diagnosed the issue correctly and indeed both pages have the same issue

Note_1:
I can "cheat" and add a function that would force the focus to an iframe in case a new one is introduced, but I don't think it would be a valid test that would test for the accessibility of the iframe

Note_2:
I did try to add the 'navigateToWebContent()' function after the button activation hoping it would send the focus to the iframe modal but it didn't help

I would love your help handling this better, maybe I'm missing something?

attached are the files to reproduce the issue,
remove the .txt from their suffix : )
[iframe_by_button.html.txt](https://github.com/user-attachments/files/17848063/iframe_by_button.html.txt)
[playwright.config.js.txt](https://github.com/user-attachments/files/17848079/playwright.config.js.txt)
[voiceOver.spec.js.txt](https://github.com/user-attachments/files/17848080/voiceOver.spec.js.txt)

**Comment by jlp-craigmorten** [comment]
Hi @eevyatarr 👋 

Couple of notes here:

- Doing some manual exploratory testing of VoiceOver + Browser combinations I observed that in Firefox (133) / Chrome (131) focus is programtically shifted to the modal text field successfully, but with Safari (17.4) it does not (regardless of whether use keyboard, mouse, or VoiceOver).
- The example you have provided doesn't actually load the modal inside an iframe unless I've misunderstood how it is to be used.
- It seems there might be an issue with `voiceOver.type()` not working as expected, for now you can work around using `page.keyboard.type()` from Playwright.

See below for a slight rewrite of your tests. Interesting if you introduce a check for the iframe being loaded via `page.frameLocator` Playwright appears to send focus to it which per your "Note_1" is not an accurate test.

```js
const { expect } = require("@playwright/test");
const { voiceOverTest: test } = require("@guidepup/playwright");

async function sleep(milliseconds = 1000) {
  await new Promise((resolve) => setTimeout(resolve, milliseconds));
}

test.use({ voiceOverStartOptions: { capture: "initial" } });

test.describe("Playwright VoiceOver custom iframe page", () => {
  test("open the iframe and type", async ({ page, voiceOver }) => {
    // Visit the test page, wait for contents to load, and then navigate to the main content.
    await page.goto("http://localhost:8081/iframe_by_button.html", {
      waitUntil: "load",
    });

    await expect(
      page.getByRole("heading", { level: 1, name: "title1" })
    ).toBeVisible();

    await voiceOver.navigateToWebContent();

    // Navigate to the "Open Modal" button.
    while (!(await voiceOver.lastSpokenPhrase()).includes("Open Modal")) {
      await voiceOver.next();
    }

    // Open the modal and expect it to be visible.
    await voiceOver.act();

    await expect(
      page.getByRole("heading", { level: 2, name: "Accessible Modal" })
    ).toBeVisible();

    // Type into the modal input field.
    // Seems investigation needed on VO typing not working.
    // await voiceOver.type("hey");
    await page.keyboard.type("hey");

    // Navigate to the submit button and interact.
    await voiceOver.next();
    await voiceOver.act();
  });
});

test.describe("Playwright VoiceOver evinced website", () => {
  test("book a demo", async ({ page, voiceOver }) => {
    await page.goto("https://evinced.com/", {
      waitUntil: "load",
    });

    await expect(
      page.getByRole("heading", { level: 1, name: "Accessibility at scale" })
    ).toBeVisible();

    await voiceOver.navigateToWebContent();

    // Navigate to the first "Book a Demo" button.
    while (!(await voiceOver.lastSpokenPhrase()).includes("Book a Demo")) {
      await voiceOver.next();
    }

    // Open the modal and expect it to be visible.
    await voiceOver.act();

    await sleep(2500);

    await expect(
      page.frameLocator('[data-testid="iframe"]').getByText("Hi there")
    ).toBeVisible();

    // Type into the modal input field.
    // Seems investigation needed on VO typing not working.
    // await voiceOver.type("hey");
    await page.keyboard.type("hey");

    // Navigate to the submit button.
    await voiceOver.next();
  });
});
```

I would recommend doing some more manual checks with Safari + VoiceOver and making amends as necessary to ensure that the focus is forced correctly by your application. From what I can see VoiceOver and Guidepup are behaving as expected.

**Comment by eevyatarr** [comment]
@jlp-craigmorten thank you so much for the quick response

1. i find the `page.keyboard.type()` to be indeed very useful 
2. i was unaware of the `voiceOver.act()` and also find it very useful as well
3. these two modification indeed solved the issue at the test "open the iframe and type"
4. but the test "book a demo" still fails even after duplicating the code you have provided, focus is still behind the modal with no text typed to the text box (note that on a manual test the modal appears to be just fine), maybe something about my setup is different then what you have tested? is there any more information i can provide?

**Comment by jlp-craigmorten** [comment]
> but the test "book a demo" still fails even after duplicating the code you have provided, focus is still behind the modal with no text typed to the text box (note that on a manual test the modal appears to be just fine), maybe something about my setup is different then what you have tested? is there any more information i can provide?

As noted above, I think your site has a bug on Safari (at least Safari 17) as focus isn't actually moving to the modal (it works on Chrome and Firefox). The test failing is expected as I don't think the behaviour is actually working on the site.

**Comment by eevyatarr** [comment]
Oh wow, I've missed that, thank you so much
